services:
  - type: web
    name: telegram-webhook-bot
    runtime: python
    buildCommand: ""
    startCommand: gunicorn main:app
    env: python
    region: oregon
    plan: free
    branch: main
    autoDeploy: true